spring:
  application:
    name: matching-booking-service

  datasource:
    url: jdbc:mysql://mysql:3306/carecircle_matching_booking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info
